# Generated by Django 5.1.6 on 2025-02-09 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'metodologia',
                'verbose_name_plural': 'metodologias',
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['nome'], name='ferramentas_nome_92db1d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('imagem', models.ImageField(blank=True, upload_to='produtos/%Y/%m/%d')),
                ('descricao', models.TextField(blank=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponivel', models.BooleanField(default=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('metodologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='ferramentas.metodologia')),
            ],
            options={
                'ordering': ['nome'],
                'indexes': [models.Index(fields=['id', 'slug'], name='ferramentas_id_03aaae_idx'), models.Index(fields=['nome'], name='ferramentas_nome_69c7f3_idx'), models.Index(fields=['criado'], name='ferramentas_criado_cec6f2_idx')],
            },
        ),
    ]
