# Generated by Django 5.1.6 on 2025-02-09 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferramentas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ferramenta',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='ferramentas/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='ferramenta',
            name='metodologia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ferramentas', to='ferramentas.metodologia'),
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('membros', models.ManyToManyField(related_name='grupos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ferramenta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ferramentas', to='ferramentas.grupo'),
        ),
        migrations.CreateModel(
            name='PDCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdcas', to=settings.AUTH_USER_MODEL)),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdcas', to='ferramentas.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='EtapaPDCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PLAN', 'Planejar'), ('DO', 'Fazer'), ('CHECK', 'Verificar'), ('ACT', 'Agir')], max_length=5)),
                ('descricao', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('pdca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ferramentas.pdca')),
            ],
        ),
    ]
